version: "3.8"

services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      - POSTGRES_DB=doc_store
      - POSTGRES_PASSWORD=secret123
      - POSTGRES_USER=myuser
    ports:
      - '5432:5432'

