version: "3.8"

services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      - POSTGRES_DB=doc_store
      - POSTGRES_PASSWORD=secret123
      - POSTGRES_USER=myuser
    ports:
      - '5432:5432'
    networks:
      - app-network

  springboot-app:
    build: .
    depends_on:
      - pgvector
    ports:
      - '8082:8082'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pgvector:5432/doc_store
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=secret123
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
