server {
  listen 80;
  server_name 18.118.119.68;

  root /usr/share/nginx/html;
  index index.html;

  # Sirve la SPA
  location / {
    try_files $uri $uri/ /index.html;
  }

  # Proxy para la API
  location /api/ {
    proxy_pass http://18.118.119.68:8081; # tu backend corriendo en 3000
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }
}
